name: Build Project

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Package project as JAR
        run: mvn -ntp -B package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: crypto-scam
          path: target/*.jar